#ifndef COMMONTOOLSSPACE_H
#define COMMONTOOLSSPACE_H

//命名空间定义
#ifndef COMMON_TOOLS_SPACE
#define COMMON_TOOLS_SPACE CommonTools
#define BEGIN_COMMON_TOOLS_SPACE namespace COMMON_TOOLS_SPACE{
#define END_COMMON_TOOLS_SPACE }
#define USE_COMMON_TOOLS_SPACE using namespace COMMON_TOOLS_SPACE;
#endif // !COMMON_TOOLS_SPACE

#endif // !COMMONTOOLSSPACE_H

